"""OTel GenAI semantic-convention attribute keys (subset used by this package)."""

# GenAI
GEN_AI_SYSTEM = "gen_ai.system"
GEN_AI_REQUEST_MODEL = "gen_ai.request.model"
GEN_AI_RESPONSE_MODEL = "gen_ai.response.model"
GEN_AI_OPERATION_NAME = "gen_ai.operation.name"
GEN_AI_REQUEST_TEMPERATURE = "gen_ai.request.temperature"
GEN_AI_REQUEST_TOP_P = "gen_ai.request.top_p"
GEN_AI_REQUEST_STREAMING = "gen_ai.request.streaming"
GEN_AI_RESPONSE_FINISH_REASON = "gen_ai.response.finish_reason"
GEN_AI_USAGE_INPUT_TOKENS = "gen_ai.usage.input_tokens"
GEN_AI_USAGE_OUTPUT_TOKENS = "gen_ai.usage.output_tokens"
GEN_AI_USAGE_TOTAL_TOKENS = "gen_ai.usage.total_tokens"
GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS = "gen_ai.usage.cache_read.input_tokens"
GEN_AI_USAGE_REASONING_OUTPUT_TOKENS = "gen_ai.usage.reasoning.output_tokens"
GEN_AI_USAGE_ESTIMATED = "gen_ai.usage.estimated"
GEN_AI_TOKEN_TYPE = "gen_ai.token.type"
GEN_AI_TOOL_NAME = "gen_ai.tool.name"
GEN_AI_TOOL_CALL_ID = "gen_ai.tool.call.id"
GEN_AI_TOOL_ARGUMENTS = "gen_ai.tool.arguments"
GEN_AI_TOOL_RESULT = "gen_ai.tool.result"
GEN_AI_INPUT_MESSAGES = "gen_ai.input.messages"
GEN_AI_OUTPUT_MESSAGES = "gen_ai.output.messages"
GEN_AI_TOOL_DEFINITIONS = "gen_ai.tool.definitions"
GEN_AI_SKILL_NAME = "gen_ai.skill.name"
GEN_AI_SKILL_ID = "gen_ai.skill.id"
GEN_AI_AGENT_NAME = "gen_ai.agent.name"
GEN_AI_CONVERSATION_ID = "gen_ai.conversation.id"
GEN_AI_STREAMING_FIRST_TOKEN_MS = "gen_ai.streaming.first_token_ms"
GEN_AI_CONTEXT_SKILL = "gen_ai.context.skill"
GEN_AI_CONTEXT_SYSTEM_PROMPT = "gen_ai.context.system_prompt"
GEN_AI_CONTEXT_USER_MESSAGES = "gen_ai.context.user_messages"
GEN_AI_CONTEXT_ASSISTANT_MESSAGES = "gen_ai.context.assistant_messages"
GEN_AI_CONTEXT_TOOL_RESULTS = "gen_ai.context.tool_results"
GEN_AI_CONTEXT_TOOL_DEFINITIONS = "gen_ai.context.tool_definitions"

# jiuwenclaw custom dimensions
JIUWENCLAW_SESSION_ID = "jiuwenclaw.session.id"
JIUWENCLAW_CHANNEL_ID = "jiuwenclaw.channel.id"
JIUWENCLAW_REQUEST_ID = "jiuwenclaw.request.id"
JIUWENCLAW_AGENT_NAME = "jiuwenclaw.agent.name"
JIUWENCLAW_DOMAIN_ID = "jiuwenclaw.domain.id"

# context compaction dimensions
GEN_AI_CONTEXT_COMPACTION_PATH = "context.compaction.path"
GEN_AI_CONTEXT_COMPACTION_PROCESSOR_TYPE = "context.compaction.processor_type"
GEN_AI_CONTEXT_COMPACTION_TOKENS_BEFORE = "context.compaction.tokens_before"
GEN_AI_CONTEXT_COMPACTION_TOKENS_AFTER = "context.compaction.tokens_after"
GEN_AI_CONTEXT_COMPACTION_TOKENS_SAVED = "context.compaction.tokens_saved"
GEN_AI_CONTEXT_COMPACTION_MESSAGES_BEFORE = "context.compaction.messages_before"
GEN_AI_CONTEXT_COMPACTION_MESSAGES_AFTER = "context.compaction.messages_after"
JIUWENCLAW_CONTEXT_ID = "jiuwenclaw.context.id"
GEN_AI_CONTEXT_MEMORY_BLOCKS = "gen_ai.context.memory_blocks"
